### ISSUE TITLE
Some Error Log

### ISSUE THREAD

**Issue by andhra21231** [amethystcraft-lab/amethystcraft-music#7]
```
/root/zack-bot/node_modules/i18n/i18n.js:491
    targetObject.locale = locales[targetLocale] ? targetLocale : defaultLocale
                        ^

TypeError: Cannot set property 'locale' of undefined
    at Object.i18nSetLocale [as setLocale] (/root/zack-bot/node_modules/i18n/i18n.js:491:25)
    at Object.<anonymous> (/root/zack-bot/src/commands/clip.js:10:6)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/zack-bot/src/main.js:70:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
```
hey @ariflitejek can you fix this ?

**Comment by xaliazhar** [comment]
P

**Comment by andhra21231** [comment]
Malah nge p

**Comment by xaliazhar** [comment]
suka-suka saya :)

**Comment by ipincamp** [comment]
punten


Pada tanggal Jum, 1 Okt 2021 pukul 19.12 aliazhar ***@***.***>
menulis:
